### PR TITLE
Refactor RSS generation and tweak inclusion rules

### PR DESCRIPTION
**Pull request by jsvine**
With the anticipation of adding additional feeds, I figured I'd refactor the code we use to generate them, introducing a new method, `generate_feed`.

While doing that, I realized it'd be helpful to have slightly more specific rules for whether an entry is included, with the goals of:

- Including all entries less than X days old (based on date of discovery)
- Excluding entries more than Y days old
- Beyond that, setting a soft threshold of Z entries ...
- ... while not arbitrarily including only some portion of a group of inspections all discovered at the same time

### CODE REVIEW

**Comment by palewire** [comment]
As long as we're using the discovered date and not the inspection date I think this is fine. Over the last few weeks I've seen inspections discovered that are dated more than a month ago.

**Comment by jsvine** [comment]
Yep, sort order is:

- Discovered date first ...
- ... then inspection date
- ... then hash_id (just to keep things deterministic)

And yeahhhh, some of these get posted to APHIS *quite* a bit after the inspection dates. https://github.com/data-liberation-project/aphis-inspection-reports/issues/36 should help understand _some_ component of that (i.e., how much of this is explained by reports themselves taking a long time to be finalized vs. finalized reports not being uploaded/released).

**Comment by jsvine** [comment]
(Oh, and yes, the `max_age_days` limit is based on the _discovered_ date, not the inspection date.)

**Comment by palewire** [comment]
👍

**Pull request merged**
